### ISSUE TITLE
Illegible text

### ISSUE THREAD

**Issue by peotr26** [Vanilla-OS/website#105]
The main page of the new website has a section where a part of the text is illegible. It seems like the *Solid* section is higher than it should be.

Here are a few screenshots:
![image](https://github.com/Vanilla-OS/website/assets/67782057/ba68c7fc-2748-4ea3-98c5-ad8c87d35c95)
![image](https://github.com/Vanilla-OS/website/assets/67782057/a0e88ede-8ad8-441d-b36e-674bebeb1ae4)
![image](https://github.com/Vanilla-OS/website/assets/67782057/1b3ab305-7fff-477d-99b2-ac53d74faa51)

I'm using Firefox 114. My screen resolution is 1080p. And I'm at 100% zoom. The issue seems to not be has bad at 70% zoom.

**Comment by GabsEdits** [comment]
We know this issue, it will be fixed in the following days.

**Comment by mirkobrombin** [comment]
Tbh I am not aware of this specific issue. Btw I just served an update which should fix problems like this.
