### ISSUE TITLE
Table of Contents links open homepage

### ISSUE THREAD

**Issue by jamiethecat** [Vanilla-OS/website#121]
When clicking on a link of the Table of Contents in a blog post will send the user to the homepage.
[Screencast from 2023-08-21 15-56-05.webm](https://github.com/Vanilla-OS/website/assets/114881134/7405e17c-6d7b-4a36-b796-5e2c8b0f1669)

**Comment by GabsEdits** [comment]
The issue has been fixed as of https://github.com/Vanilla-OS/website/commit/80d47c73a8f9fd576f4fed3a025b1d60473e3469
