### ISSUE TITLE
Rethinking the Contributors List

### ISSUE THREAD

**Issue by GabsEdits** [Vanilla-OS/website#123]
The Contributors List is a page that showcase all of the contributors across Vanilla OS, currently, the pages isn't updated every week like it used to, with that, I was thinking while bringing the weekly indexing back, to also refresh the page with the idea of a mini [team page](https://vanillaos.org/team). I made a quick concept of how will something like this should look, my idea was like I said earlier an mini team page, the same idea, but with usernames, names and profile picture. And that will look something like this: 

![image](https://github.com/Vanilla-OS/website/assets/110247388/960f0396-a124-4909-a73e-9593a2b079e8)

I also have an idea in mind with a GitHub link under the profile picture, kind of like in the Team page, and maybe other links like website or X (Twitter) and others, as they can be fetched along side the others using the GitHub API. Others ideas are welcome :)

**Comment by GabsEdits** [comment]
With what I said from yesterday, the links should look something like this:

![Screenshot](https://github.com/Vanilla-OS/website/assets/110247388/f177445f-b117-4d50-b307-097892b6120f)

Please keep in mind as this is not the final version of the design, we are still discussing it :)

**Comment by GabsEdits** [comment]
As we discussed it more, we came to the idea of an fully clickable card, and to avoid fishy links we had the idea to jut have the GitHub link, and it will look like this:

![card](https://github.com/Vanilla-OS/website/assets/110247388/898f877c-8898-4fd9-aed2-fe93a0fd2dbf)

Our idea was to make it compact as the list will be (and already is) really big, we will have over 140 card so we need to make it look good an not too big, this is the dark and light look for 3 cards per line:

![dl-look](https://github.com/Vanilla-OS/website/assets/110247388/c42b0eca-80d5-4e63-ab95-e6f61004a8a3)

Please do note that all of the shadows are made just for the concept, on the website it will use the build in. For now at least this is how it will look, any other ideas are welcome :)

**Comment by mirkobrombin** [comment]
Looks good to me

**Comment by GabsEdits** [comment]
> Looks good to me

Thanks! Glad you like it! We have a whole discussion in the design channel and I'd love to also hear your opinion :)
There is an idea instead to use big cards we can use this smaller ones:

![Single Card](https://github.com/Vanilla-OS/website/assets/110247388/df286c09-bb2e-4f59-a936-ad745f57551e)

They are smaller and well use less space, so it will mean that the page will be not as long, it can look something like this:

![Page Look](https://github.com/Vanilla-OS/website/assets/110247388/a659907d-4040-4808-8382-52c8b6ac9595)

Should we go with this? Most people like it :)

**Comment by GabsEdits** [comment]
With the Pull Request here I will show a quick screenshot of the new page:

![image](https://github.com/Vanilla-OS/website/assets/110247388/3d3267ca-70c1-4245-a4e3-e1e830b62f99)
