### ISSUE TITLE
Blog does not work with Firefox

### ISSUE THREAD

**Issue by Andanan** [Vanilla-OS/website#136]
When clicking on the "Blog" link in the nav area or accessing https://vanillaos.org/blog directly. Nothing happens (link) or an empty page is shown (direct access).
The web console shows an error:

```
TypeError: error loading dynamically imported module: https://vanillaos.org/assets/Blog-505bc001.js [index-d5f25c59.js:5:21181](https://vanillaos.org/assets/index-d5f25c59.js)
    oe https://vanillaos.org/assets/index-d5f25c59.js:5
    fe https://vanillaos.org/assets/index-d5f25c59.js:5
```

FF version: 118.0.1 (Flatpak)

Works fine in Chromium and weirdly in the Tor Browser so I guess it can't be a fundamental Firefox thing.
Can someone reproduce this?

**Comment by GabsEdits** [comment]
> When clicking on the "Blog" link in the nav area or accessing https://vanillaos.org/blog directly. Nothing happens (link) or an empty page is shown (direct access). The web console shows an error:
> 
> ```
> TypeError: error loading dynamically imported module: https://vanillaos.org/assets/Blog-505bc001.js [index-d5f25c59.js:5:21181](https://vanillaos.org/assets/index-d5f25c59.js)
>     oe https://vanillaos.org/assets/index-d5f25c59.js:5
>     fe https://vanillaos.org/assets/index-d5f25c59.js:5
> ```
> 
> FF version: 118.0.1 (Flatpak)
> 
> Works fine in Chromium and weirdly in the Tor Browser so I guess it can't be a fundamental Firefox thing. Can someone reproduce this?

Seems to work fine for me. Sometimes this happens to Vue.js websites, try refreshing the website and clearing cache. Tell me if it helped

**Comment by Andanan** [comment]
Sadly it did not help. If it's not reproducible it's probably just an error in my local setup. Anyway... By using other browsers there is a workaround, so I guess the issue can be closed. It's not optimal but good enough for now.
