### ISSUE TITLE
Alpha download page doesn't load with uBlock annoyances filter

### ISSUE THREAD

**Issue by jamiethecat** [Vanilla-OS/website#149]
The page https://vanillaos.org/download/orchid/alpha doesn't load with the EasyList annoyances filter enabled on uBlock. This shouldn't be breaking a website.

**Comment by mirkobrombin** [comment]
To be fair a 3rd party tool should not break a website as well. Anyway to give some more details, this should disappear while we switch to [SSR](https://vuejs.org/guide/scaling-up/ssr.html), providing static pages.

**Comment by wyndon** [comment]
Should be closed ? https://github.com/Vanilla-OS/website/commit/d08769e6a8267f0b512110a9fe95b5a02ce666dc

**Comment by jamiethecat** [comment]
> Should be closed ? [d08769e](https://github.com/Vanilla-OS/website/commit/d08769e6a8267f0b512110a9fe95b5a02ce666dc)

Correct, thanks!
