### ISSUE TITLE
Provide Feed RSS

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/website#15]

**Comment by botorfj** [comment]
thank you

**Comment by juxuanu** [comment]
https://github.com/jekyll/jekyll-feed ?

**Comment by kbdharun** [comment]
> https://github.com/jekyll/jekyll-feed ?

Exactly, I implemented it, Working on updating some old posts locally. Will be available soon on the website.

**Comment by vendillah** [comment]
Was the rss feed intentionally omitted from the updated version of the website - has the support for it been dropped? I don't find any feed, nor any reference as to its change. Perhaps it was simply forgotten?
