### ISSUE TITLE
90 days offline - Main repository

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/website#152]
The Main Repository is reporting it has been offline for 90 days.

https://status.vanillaos.org

![Screenshot 2023-12-19 at 15-14-45 Vanilla OS status](https://github.com/Vanilla-OS/website/assets/61557098/dd2c1d3d-f01c-4e3b-85e8-12a9ef33a63b)

**Comment by mirkobrombin** [comment]
That repo was used by Orchid in its first days. We then switched it to repo2. I fixed it, thanks for reporting.
