### ISSUE TITLE
cant use website without javascript enabled

### ISSUE THREAD

**Issue by ashleyirispuppy143** [Vanilla-OS/website#159]
i am on GNU icecat 115 and the website seems to not work without non-free javascript enabled - would there be a fix for that?

**Comment by mirkobrombin** [comment]
Hi, the whole website is JavaScript (vuejs), we can't do anything here, sorry. For now you need to find a way to enable JavaScript or use a different browser.

--

Closed by mistake.

**Comment by ashleyirispuppy143** [comment]
doesnt um https://vuejs.org/guide/scaling-up/ssr.html  exist?

**Comment by mirkobrombin** [comment]
Sure, we're using SSR now but not everything has been converted. We currently don't have the effort to put in to do a full SSR conversion. We also plan to move to NuxtJS which has a feature to achieve full static website generation, but can't put effort on that too.
