### ISSUE TITLE
no link to the forums

### ISSUE THREAD

**Issue by 2-www** [Vanilla-OS/website#181]
on https://vanillaos.org/community:
> We have both a Discord server and Forums but our community is on Discord, a cross-platform voice and text chat platform designed for community of all sizes.

but i can't find the link to the forum anywhere on the website

**Comment by kbdharun** [comment]
> on https://vanillaos.org/community:
> 
> > We have both a Discord server and Forums but our community is on Discord, a cross-platform voice and text chat platform designed for community of all sizes.
> 
> but i can't find the link to the forum anywhere on the website

The paragraph you enclosed above means the Forums feature within the Discord server, which allows asking questions and much more. (Maybe I will rephrase the wording of it later)

Atm we don't have a dedicated hosted forum, the plan is to have one in future. We do have an official subreddit, but it is only maintained/moderated by a few team members including myself (as most of the core developers don't use Reddit frequently).

**Comment by 2-www** [comment]
do you have a bridge perhaps? i can't join discord (it just displays "something went wrong")

**Comment by mks-h** [comment]
> We have both a Discord server and Forums but our community is on Discord …

This part of the message doesn't make sense, because:
a) "a Discord server" and "Forums" look like two unrelated things
b) the "but" in "but our community..." is supposed to negate the first part of the sentence, yet it doesn't

>… , a cross-platform voice and text chat platform designed for community of all sizes.

And the rest of the paragraph is also weird, being a very generic advertising of Discord for no reason.

**Comment by mirkobrombin** [comment]
We do have a forum, that is inside our Discord server ([ref](https://discord.com/blog/forum-channels-space-for-organized-conversation)). We do have plans to host a forums software (like Discourse, Flarum, whatever) but that will happen in the future.

> And the rest of the paragraph is also weird, being a very generic advertising of Discord for no reason.

And no, that's not an adv.

**Comment by 2-www** [comment]
why was this marked as completed? it was not changed, the wording on the website is still the same and i can't join

**Comment by 2-www** [comment]
@mks-h do you by chance know of any ukranian language chat about vanilla?

**Comment by mks-h** [comment]
> why was this marked as completed? it was not changed, the wording on the website is still the same and i can't join

Join Discord using "Join Discord" button on the page you linked, and you will find "forums" channel there, at the "main area".

> @mks-h do you by chance know of any ukranian language chat about vanilla?

Nope, sorry. Not that I ever looked for one. There are some active Ukrainians on the official Discord, tho.

**Comment by 2-www** [comment]
this is what discord displays:
![❌️ Ой, щось пішло не так](https://github.com/Vanilla-OS/website/assets/112013524/f241dee5-29c4-428d-9b28-36d8a14572a1)

**Comment by mks-h** [comment]
@2-www this is weird. Please try this link: https://discord.gg/UJvRhRsZ

**Comment by 2-www** [comment]
![неможливо прийняти запрошення](https://github.com/Vanilla-OS/website/assets/112013524/cd032d41-360b-4380-a78b-a447c3c98bf7)

**Comment by mks-h** [comment]
It seems to be a Discord issue on your side. From some articles I've read, it may be due to exceeding 100 servers limit, or making too many requests, or whatever else. Maybe you can try to join from "Discoverable Servers"? It is the last button in the list of servers (a compass icon), and it allows to search for a server. Search "Vanilla OS" there and try joining that way.
