### ISSUE TITLE
Team member cards' have a "get-involved-funding" link which is not used

### ISSUE THREAD

**Issue by mks-h** [Vanilla-OS/website#182]
See [line 138 of Teams page](https://github.com/Vanilla-OS/website/blob/v2/src/views/Team.vue#L138). It adds a link to `"get-involved-funding"` for every card, but the link is not used in the card itself. To use this link, `type: "clickable"` has to be passed as well, but it will make every line underlined.

**Comment by mirkobrombin** [comment]
Yes you are right, thanks for reporting

**Comment by wesleybertipaglia** [comment]
Hi guys, this issue was closed?

**Comment by mirkobrombin** [comment]
![image](https://github.com/user-attachments/assets/ffe1c928-7cde-4cc8-b5da-977d09526f27)
no

**Comment by mirkobrombin** [comment]
Yes
