### ISSUE TITLE
discord link is not working

### ISSUE THREAD

**Issue by 2-www** [Vanilla-OS/website#187]
i tried creating another account, there are no chats on it, but i still have an error when i try to join:
![couldn't accept invite](https://github.com/Vanilla-OS/website/assets/112013524/4de3b4ed-6cfc-43df-829e-201b74675bb2)

**Comment by GabsEdits** [comment]
It seems to be a issue for you locally 🤔 . I've reproduced it and it worked (using the [Join Discord ->](https://discord.gg/vanilla-os-1023243680829681704) in <https://vanillaos.org/community>
