### ISSUE TITLE
Feature Request: A Comparison to Other Popular Immutable Distro

### ISSUE THREAD

**Issue by Malix-Labs** [Vanilla-OS/website#202]
# Feature Request

A Comparison to Other Popular Immutable/Atomic Distro

## References

- [Awesome List of Immutables/Atomic Linux Distributions](https://github.com/castrojo/awesome-immutable#distributions)

**Comment by mirkobrombin** [comment]
Personally I don't like making comparisons because they are easily questionable. We have this page for extra details: https://vanillaos.org/nerd-info

**Comment by Malix-Labs** [comment]
Understandable
