### ISSUE TITLE
Comparison with other OSs?

### ISSUE THREAD

**Issue by upintheairsheep** [Vanilla-OS/website#267]
On the website, could you compare VOS with it's alternatives, like Windows, macOS, other Linux distros, and ChromeOS? Vanilla OS's architecture really reminds me of chromeOS (having all the security that comes with it), but excluding the fact that if Chrome browser crashes on ChromeOS, everything goes down with it, and Chrome likely has much more control over the OS than it should. If Verified Boot fails on ChromeOS, it will delete all user data with it without the user's consent, while Vanilla OS just tells the user and doesn't delete any data.

**Comment by mirkobrombin** [comment]
Thanks for the suggestion. Comparisons can't be reliable, each product is unique and will base the whole comparison on its values.
