### ISSUE TITLE
Make a FAQ page

### ISSUE THREAD

**Issue by delight-aug** [Vanilla-OS/website#27]
Make a FAQ page with the long list of questions, maybe divided into sections as needed. Keep a little FAQ section on the main page, with some first questions about the OS + a link to the FAQ page.

This will allow to send people to the FAQ first, so maybe we will get less questions about the manual partitioning and other highly requested features. It would also help to be able to link to a specific question.

Keeping all FAQs on the home page will be weird IMHO.

**Comment by kbdharun** [comment]
> Make a FAQ page with the long list of questions, maybe divided into sections as needed. Keep a little FAQ section on the main page, with some first questions about the OS + a link to the FAQ page.
> 
> This will allow to send people to the FAQ first, so maybe we will get less questions about the manual partitioning and other highly requested features. It would also help to be able to link to a specific question.
> 
> Keeping all FAQs on the home page will be weird IMHO.

Yeah, this is something we could add to the roadmap.
