### ISSUE TITLE
The hover color of the `.blog-posts article` is too bright for dark variant

### ISSUE THREAD

**Issue by mjoork** [Vanilla-OS/website#35]
![Bright hover color](https://user-images.githubusercontent.com/20644474/211098262-565e65d3-5150-49ee-ba99-0429dc798e77.png)

I think we can agree that the color is too bright, but the color with which it should be replaced is subjective.

I am not sure if there's a palette somewhere, so `#363636` (which is lighter than `#2d2d2d` by the same amount as `#2d2d2d` is lighter than `#242424`) comes to mind.

However, `#363636` looks very similar to `#2d2d2d` to me...

![Way too little contrast ratio](https://user-images.githubusercontent.com/20644474/211100069-51236552-d7b4-4242-a8e9-6c46ddd90af2.png)

... so it might be better to go for `#3f3f3f` or something even brighter, but no brighter than `#505050`. 

![Less brighter color](https://user-images.githubusercontent.com/20644474/211099793-ef6e95e8-c908-4c95-998f-637605bca77e.png)

**Comment by shubhsharma19** [comment]
It has been fixed I guess you can close this now may be?
