### ISSUE TITLE
[proposal]  New web built with astro + tailwindcss

### ISSUE THREAD

**Issue by alinpr18** [Vanilla-OS/website#42]
## Why?

Jekyll being a powerfull tool makes it very defficult for new developer who want to start open source to contribute.

Astro is a powerful tool that allows you to make websites agnostic to the frameworks you use and that allows multiple collaboration by not depending on a single tool (frameworks).

For days I took the challenge of recreating the website in this technology and so far it is 80% complete with better performance and fully responsive.

The code is available in my repository: https://github.com/alinpr18/vanillaos-website
Live demo here: https://musical-torrone-a895f9.netlify.app/

The community is free to choose if this change is necessary or not, however, I only did this for educational purposes.

**Comment by bketelsen** [comment]
nicely done!

**Comment by mirkobrombin** [comment]
Thank you so much for the effort, tailwindcss is a great framework and this one is definitely improving immensely.

I'd like to migrate to your code base but there are a few points to resolve before this happens:
- animations are gone
- the spacing as the size of the fonts in the current site, are part of the mockup that I designed for the visual impact of the product and I think they should be re-integrated

I assume this is an initial release and will see updates in the future, mine are more than tasks to deal with.

**Comment by pietrodicaprio** [comment]
I was looking few days ago into Astro and looks interesting. Tailwind is a good choice too.
+1 for me!

**Comment by alinpr18** [comment]
> Thank you so much for the effort, tailwindcss is a great framework and this one is definitely improving immensely.
> 
> I'd like to migrate to your code base but there are a few points to resolve before this happens:
> 
> * animations are gone
> * the spacing as the size of the fonts in the current site, are part of the mockup that I designed for the visual impact of the product and I think they should be re-integrated
> 
> I assume this is an initial release and will see updates in the future, mine are more than tasks to deal with.

By chance, do you have the figma of the project?. It would help me a lot for the pixel perfect

**Comment by mirkobrombin** [comment]
Sadly it was lost 😶‍🌫️

**Comment by mirkobrombin** [comment]
We switched to Vuejs and Vite.
