### ISSUE TITLE
Feature Request : Add a community discussion panel.

### ISSUE THREAD

**Issue by abuhuraira0099** [Vanilla-OS/website#45]
We need a community section where we can discuss issues and topics related to VanillaOS.

**Comment by kbdharun** [comment]
Disqus?

**Comment by mirkobrombin** [comment]
Our forum is available on discord. https://discord.gg/3cD2Q7Ht3S

**Comment by gonzoknows** [comment]
> Our forum is available on discord. https://discord.gg/3cD2Q7Ht3S

Need something that is easily searchable, discord isn't a solution. Can you enable GitHub discussions for the time being so it at least pops up in search engines SEO? Discord has no SEO nor is it open to view

**Comment by mirkobrombin** [comment]
![image](https://user-images.githubusercontent.com/9479903/216712773-f3ff4692-a186-4b6c-b8cd-a4cda310b9b5.png)

For technical discussions we use the proper repository issue tracker, while for guides there are handbook and documentation.

**Comment by abuhuraira0099** [comment]
Discord is a bad example to be a community meeting point for a FOSS project. You should at least consider to open a FOSS oriented place such as Matrix or Telegram group if you don't have enough resources to create a discourse channel.

**Comment by kbdharun** [comment]
> Discord is a bad example to be a community meeting point for a FOSS project. You should at least consider to open a FOSS oriented place such as Matrix or Telegram group if you don't have enough resources to create a discourse channel. 

We do indeed have a matrix room (with space) for the docs team at #vanillaos-docs:matrix.org.

Matrix even though good has still a lot of features to catch up with Discord, as someone part of a lot of rooms in matrix as well as IRC it is really inefficient in the long run as they don't have a lot of mirrors. Telegram doesn't have spaces or separate rooms and it can quickly become a mess IMO.

Discourse any be the solution for the future. But for now Discord Forums are fine.

**Comment by gonzoknows** [comment]
> > Discord is a bad example to be a community meeting point for a FOSS project. You should at least consider to open a FOSS oriented place such as Matrix or Telegram group if you don't have enough resources to create a discourse channel.
> 
> We do indeed have a matrix room (with space) for the docs team at #vanillaos-docs:matrix.org.
> 
> Matrix even though good has still a lot of features to catch up with Discord, as someone part of a lot of rooms in matrix as well as IRC it is really inefficient in the long run as they don't have a lot of mirrors and doesn't work well with bridging and webhooks. Telegram doesn't have spaces or separate rooms and it can quickly become a mess IMO.
> 
> Discourse may be the solution for the future. But for now Discord Forums are fine.

Even [revolt.chat](https://revolt.chat/) is a better alternative than discord. Considering it's FOSS and don't do all the craziness discord does
