### ISSUE TITLE
[Feature] Color of the top navbar items change to #fbbe4e when hover in dark mode

### ISSUE THREAD

**Issue by shubhsharma19** [Vanilla-OS/website#54]
Before:
![2023-02-14 14_32_00-Vanilla OS - Brave](https://user-images.githubusercontent.com/69891912/219101883-ef50b1e1-e6ff-45a1-b239-370a4d796382.png)

After:
![2023-02-14 14_46_57-Vanilla OS - Brave](https://user-images.githubusercontent.com/69891912/219101910-5760a2f8-da06-47d2-8ab9-3cfe8fc21c1a.png)

Why #fbbe4e because its the color of the logo of Vanilla OS.
![2023-02-14 14_51_47-Color Picker](https://user-images.githubusercontent.com/69891912/219102044-4d1ef484-cc95-46c0-b770-79a6c306b62b.png)

If you like this feature I have raised a PR for this:
#53

**Comment by mirkobrombin** [comment]
closed by #53
