### ISSUE TITLE
Drop-down menu showing incorrectly

### ISSUE THREAD

**Issue by LinuxGamer** [Vanilla-OS/website#6]
![0D729614-AA17-4494-9E6F-20C5E11EC242](https://user-images.githubusercontent.com/83363242/198256501-de3aaf86-1a1d-4113-817e-90fcb677561d.jpeg)
The three dot menu doesn't show in the assumed correct way.

**Comment by mirkobrombin** [comment]
fixed by https://github.com/Vanilla-OS/website/commit/3ee70297b47649d94b721389938cbd6b811cd04f
