### ISSUE TITLE
The Discord server link doesnt work

### ISSUE THREAD

**Issue by hirusha-adi** [Vanilla-OS/website#7]
Link from website: https://discord.com/invite/XwuJ3Y9B

![image](https://user-images.githubusercontent.com/36286877/198865580-d2162f1b-bd2f-4f21-84a3-15f27867af06.png)

**Comment by mirkobrombin** [comment]
fixed by https://github.com/Vanilla-OS/website/commit/50dc2835ba733eb4183c5dafcf1adbcdacfe70de
