### ISSUE TITLE
More website links in assets/js/contributors.js

### ISSUE THREAD

**Issue by orowith2os** [Vanilla-OS/website#70]
It would be nice to have support for more sites in the team page on the website: https://vanillaos.org/team

I have the following in mind:

- [ ] Website
- [ ] Fediverse: https://github.com/Vanilla-OS/website/pull/71
- [ ] GitLab
- [ ] Email

I don't plan on suggesting websites like Twitter or Discord, and am generally uninterested about such things. Having a Fediverse link and maybe a Matrix user would be better.

**Comment by kbdharun** [comment]
I agree with this, it would indeed be nice as most of us have public accounts.
