### ISSUE TITLE
Announcement section visible at responsive when scrolled to bottom... Not properly responsive

### ISSUE THREAD

**Issue by AbhayaShankar** [Vanilla-OS/website#91]
https://github.com/Vanilla-OS/website/assets/113185442/22fa5ee3-30a4-4b2d-b32c-5d588e0741db

**Comment by AbhayaShankar** [comment]
Reason -->  Navbar overflow...

**Comment by anand346** [comment]
Please assign this issue to me , I would love to solve it

**Comment by mirkobrombin** [comment]
closed in branch v2
